### ISSUE TITLE
jPanelMenu Stops HTML5 Videos in Chrome From Auto/Playing

### ISSUE THREAD

**Issue by rooksstrife** [acolangelo/jPanelMenu#104]
With this in the code:
var jPM = $.jPanelMenu({
    menu: 'nav .container',
    trigger: '#menu-button',
    openPosition: '280px',
    closeOnContentClick: 'true',
});

jPM.on();

HTML5 Video will not auto play in Chrome (works in all other browsers).  When I take it out or just the function call "jPM.on();" the video works.  I renamed the variable jPM just in case = fail.

I am not sure what is causing the issue.  I can provided more details if needed.

**Comment by acolangelo** [comment]
This is probably happening because the plugin is manipulating the DOM when `.on( )` is called (in order to set up everything appropriately). Use the [`afterOn`](http://jpanelmenu.com/#options-afterOn) option to provide a method to be run after the plugin is turned on. In that method, you can take the necessary steps to begin playing the video!
