### ISSUE TITLE
jPanelMenu ruins the background of Bootstrap

### ISSUE THREAD

**Issue by PhilipAnd** [acolangelo/jPanelMenu#22]
When enabling jPanelMenu the overlay doesn't work. When the overlay is open it will have the background color rest on top of the whole page.

To better explain the issue, I have created this fiddle: http://jsfiddle.net/tDGrn/3/ 

If you comment out jPM.on() it works.

**Comment by rodrigoAbril** [comment]
Hi guys, If anyone still has this problem

Explanation: 
The actual bug is related to how <b>fixed position</b>  works different on elements affected by translate3d, this causes all fixed elements like the modal to misbehave . (see http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue)

-as support for fixed elements was removed you can try manually removing the style property from element.jPanelMenu-panel while the modal is opened.

Fix:

<pre>
.modal-open .jPanelMenu-panel {
    position:static!important;
    -webkit-transform:none!important;
    transform:none!important;
}
</pre>

(Edited after reading that the plugin dropped fixed position support)
